# Generated by Django 5.2.8 on 2025-11-25 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القسم')),
                ('governorate', models.CharField(max_length=255, verbose_name='المحافظة')),
                ('manager_name', models.CharField(max_length=255, verbose_name='اسم مدير أو رئيس القسم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قسم الاستمارة',
                'verbose_name_plural': 'أقسام الاستمارات',
            },
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الموظف')),
                ('job', models.CharField(max_length=255, verbose_name='العمل')),
                ('email', models.EmailField(max_length=255, verbose_name='الإيميل المستخدم في النظام')),
                ('permission', models.CharField(choices=[('admin', 'مدير'), ('user', 'مستخدم'), ('viewer', 'مشاهد')], default='user', max_length=50, verbose_name='الصلاحية')),
                ('permission_to_add', models.CharField(blank=True, max_length=255, verbose_name='صلاحية تحتاج إلى إضافة')),
                ('permission_to_delete', models.CharField(blank=True, max_length=255, verbose_name='صلاحية تحتاج إلى حذف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageforms.formdepartment', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'تفاصيل الموظف',
                'verbose_name_plural': 'تفاصيل الموظفين',
            },
        ),
    ]
