# Generated by Django 5.2.8 on 2025-11-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdepartment',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='إيميل رئيس القسم'),
        ),
        migrations.AddField(
            model_name='formdepartment',
            name='manager_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم هاتف رئيس القسم'),
        ),
    ]
